### ISSUE TITLE
Trying to install the web server...

### ISSUE THREAD

**Issue by foisys** [dfci-cccb/mev#1051]
Hi,

I am trying to install the mev server on an Ubuntu 16.04 VM to test it before possibly installing locally... I am following the instructions and hit a wall :-( I have installed R and it is available on the PATH but when I try running maven (with the -e flag), I get this:

[DEBUG] : Launching R script /tmp/mev-r-3481821357432335705.R using Rscript /tmp/mev-r-3481821357432335705.R
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.101 sec <<< FAILURE! - in edu.dfci.cccb.mev.r.mock.cli.CliRScriptEngineTest
helloWorld(edu.dfci.cccb.mev.r.mock.cli.CliRScriptEngineTest)  Time elapsed: 0.089 sec  <<< ERROR!
javax.script.ScriptException: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at edu.dfci.cccb.mev.r.mock.cli.CliRScriptEngine.eval(CliRScriptEngine.java:89)
	at edu.dfci.cccb.mev.r.mock.cli.CliRScriptEngine.eval(CliRScriptEngine.java:70)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at edu.dfci.cccb.mev.r.mock.cli.CliRScriptEngineTest.helloWorld(CliRScriptEngineTest.java:38)

So it can't find Rscript but I know that it is there, same path as R... So maven fails at the MeV R Integration step and can't complete:

[INFO] MeV R Integration .................................. FAILURE [  2.713 s]

Any inputs to solve this?

Best regards

S Foisy
Project  Manager
Bioinformatics
Montreal Heart Institute

**Comment by lev-kuznetsov** [comment]
There's no ```Rscript``` available on the execution path.

**Comment by foisys** [comment]
Hi,

Yes there is Rscript on the path:

bioubuntu@bioubuntu:~$ Rscript --version
R scripting front-end version 3.3.2 (2016-10-31)

So what's next?

S

**Comment by lev-kuznetsov** [comment]
Try launching the exact command line from the debug statement (Rscript /tmp/mev-r-3481821357432335705.R from above) in the same terminal as the failed maven. If that works I'm quite frankly lost; you can skip tests via -DskipTests flag to maven
