### ISSUE TITLE
No VOOM plot displayed

### ISSUE THREAD

**Issue by FrancesWong** [dfci-cccb/mev#1059]
Hi, 

I'm using mev.tm4.org to analyze some time series data and but after the VOOM analysis, the plot at the top of the page is not displayed. The gene table is generated below and I can switch tabs to the heatmap associated, both these seem to be displaying fine. (Screenshot image: https://drive.google.com/file/d/0B2LCg5cr88QhdmFGeUtENG9Bdmc/view?usp=sharing) 

To get to this point, I uploaded my dataset (5 timepoints, 3 replicates each, first timepoint 0hr is untreated control), normalized with deseq, and used VOOM to compare the first and last timepoint. There's 257 pages of genes in the output table so I'm hoping the analysis went through. 

The hardware I'm using is Lenovo Carbon X1, Windows 10. I've also tried it with an older macbook pro, 2011, 10.7.5 and couldn't generate the VOOM graphs. 

Thank you very much in advanced!

**Comment by apartensky** [comment]
Hi Frances,
I see the issue on your screen shot, but cannot reproduce. Can you post the output of the Chrome's log console? To do so run the VOOM analysis. Then right-click anywhere on the page and select "Instpect" option (the last one on the menu). That will open a pane in Chrome with the console output. Select "Error" filter and copy the contents. Post here or email to mev@jimmy.harvard.edu
Thank you,
Antony

**Comment by FrancesWong** [comment]
I've tried to wipe the dataset and start over and still the output is missing. A coworker of mine has the same problem on her windows while another one can get it working on his mac pro. 

Error output: 

Error: Failed to execute 'querySelector' on 'Element': 'g#0hrs-outliers' is not a valid selector.
    at d3_select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:23788)
    at SVGGElement.<anonymous> (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:44:3313)
    at Array.d3_selectionPrototype.select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:24638)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:2083
    at Array.map (native)
    at drawQuantile (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:1980)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6678
    at Array.map (native)
    at Object.draw (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6556)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:9666
(anonymous) @ VM35:56
VM35:56 Error: [ng:areq] Argument 'AnalysesVM' is not a function, got undefined
http://errors.angularjs.org/1.4.12/ng/areq?p0=AnalysesVM&p1=not%20aNaNunction%2C%20got%20undefined
    at <anonymous>:53:843
    at assertArg (<anonymous>:53:14698)
    at assertArgFn (<anonymous>:53:14900)
    at <anonymous>:55:18388
    at <anonymous>:81:7360
    at invokeLinkFn (<anonymous>:55:10815)
    at nodeLinkFn (<anonymous>:54:28167)
    at compositeLinkFn (<anonymous>:54:18486)
    at <anonymous>:54:17199
    at updateView (<anonymous>:81:5862)
(anonymous) @ VM35:56
3VM35:56 Error: Failed to execute 'querySelector' on 'Element': 'g#0hrs-outliers' is not a valid selector.
    at d3_select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:23788)
    at SVGGElement.<anonymous> (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:44:3313)
    at Array.d3_selectionPrototype.select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:24638)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:2083
    at Array.map (native)
    at drawQuantile (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:1980)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6678
    at Array.map (native)
    at Object.draw (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6556)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:9666
(anonymous) @ VM35:56
VM35:56 TypeError: Cannot read property 'groups' of undefined
    at Object.draw (views.dataset.module.js:336)
    at views.dataset.module.js:336
    at processQueue (<anonymous>:56:26291)
    at <anonymous>:56:26558
    at Scope.$eval (<anonymous>:57:7520)
    at Scope.$digest (<anonymous>:57:5320)
    at <anonymous>:57:7663
    at completeOutstandingRequest (<anonymous>:54:5800)
    at <anonymous>:54:8899
(anonymous) @ VM35:56
997views.dataset.module.js:44 Error: <rect> attribute height: Expected length, "NaN".
attrConstant @ views.dataset.module.js:44
3VM35:56 Error: Failed to execute 'querySelector' on 'Element': 'g#0hrs-outliers' is not a valid selector.
    at d3_select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:23788)
    at SVGGElement.<anonymous> (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:44:3313)
    at Array.d3_selectionPrototype.select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:24638)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:2083
    at Array.map (native)
    at drawQuantile (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:1980)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6678
    at Array.map (native)
    at Object.draw (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6556)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:9666
(anonymous) @ VM35:56
http://google-refine.googlecode.com/svn/support/releases.js Failed to load resource: the server responded with a status of 404 (Not Found)
VM35:56 Error: Failed to execute 'querySelector' on 'Element': 'g#0hrs-outliers' is not a valid selector.
    at d3_select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:23788)
    at SVGGElement.<anonymous> (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:44:3313)
    at Array.d3_selectionPrototype.select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:24638)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:2083
    at Array.map (native)
    at drawQuantile (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:1980)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6678
    at Array.map (native)
    at Object.draw (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6556)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:9666
(anonymous) @ VM35:56
https://cdn.syndication.twimg.com/timeline/profile?callback=__twttr.callbac…reen_name=webmev&suppress_response_codes=true&t=1649755&with_replies=false Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
http://mev.tm4.org/dataset?format=json Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
VM35:56 Error: Failed to execute 'querySelector' on 'Element': 'g#0hrs-outliers' is not a valid selector.
    at d3_select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:23788)
    at SVGGElement.<anonymous> (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:44:3313)
    at Array.d3_selectionPrototype.select (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:47:24638)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:2083
    at Array.map (native)
    at drawQuantile (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:1980)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6678
    at Array.map (native)
    at Object.draw (http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:6556)
    at http://mev.tm4.org/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:336:9666
(anonymous) @ VM35:56

Hope this helps! 

Thanks, 
-Frances

**Comment by apartensky** [comment]
Frances, I was able to reproduce your issue. The problem is that your selection names start with a number. This is an issue will fix in MeV. But as a workaround, try naming your selections starting with letters, so "hrs0" instead of "0hrs", and then running VOOM.

**Comment by FrancesWong** [comment]
Ah, thank you very much for pinpointing the issue! I renamed the samples and I was able to get the proper plots. 

By the way, with the numerical names, I wasn't getting EdgeR plot either, but renaming the samples fixed this issue as well. Just pointing out for when you fix the problem. 

Thank you very much for your prompt support! 
-Frances

**Comment by lev-kuznetsov** [comment]
Reopen as it's an ongoing bug

**Comment by momeanaskor** [comment]
hi
I am trying to download MEV
It no longer available?
could you please let me know how to download and install MEV?
Thanks
