### ISSUE TITLE
double-click the MeV app does not work

### ISSUE THREAD

**Issue by nana-marinbio** [dfci-cccb/mev#1083]
I installed MeV_4_8_1 in mac os sierra 10.12.6 but cannot launch it with double-click the MeV app.
I have java 1.8 and can run other apps like Jalview.
If I double-click JavaApplicationStub i get the following message in terminal:

Last login: Sun Oct 29 11:47:31 on ttys001
/Applications/MeV_4_8_1/MeV.app/Contents/MacOS/JavaApplicationStub ; exit;
iMac-de-nana:~ AnaPaula$ /Applications/MeV_4_8_1/MeV.app/Contents/MacOS/JavaApplicationStub ; exit;
[JavaAppLauncher Error] CFBundleCopyResourceURL() failed loading MRJApp.properties file
[JavaAppLauncher Error] CFBundleCopyResourceURL() failed while getting Resource/Java directory
[LaunchRunner Error] No main class specified
[JavaAppLauncher Error] CallStaticVoidMethod() threw an exception
Exception in thread "main" java.lang.NullPointerException
	at apple.launcher.LaunchRunner.run(LaunchRunner.java:113)
	at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
	at apple.launcher.JavaApplicationLauncher.main(JavaApplicationLauncher.java:61)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by nana-marinbio** [comment]
Can anyone help with this?
Thanks
